### ISSUE TITLE
Incompatability with Galaxy 19.05

### ISSUE THREAD

**Issue by monprin** [galaxyproject/ansible-galaxy-tools#65]
Hello,

It would seem that this role has been broken by Galaxy 19.05. In the `manage_bootstrap_user.py` script, the line `from galaxy.web import security` produces the following error:

```
Traceback (most recent call last):
  File "manage_bootstrap_user.py", line 21, in <module>
    from galaxy.web import security
ImportError: cannot import name security
```

And sure enough when you check the lib of galaxy, the security module has been removed (PR: galaxyproject/galaxy#7560). I did not check for other incompatibilities in the script.

Is there any work around or plan to update this role for compliance with 19.05? It otherwise worked well in 19.01.

Thank you!

**Comment by drosofff** [comment]
I think PR #61 is addressing this issue.

**Comment by monprin** [comment]
Perfect, totally missed that, thank you!
