### ISSUE TITLE
install_tool_shed_tools.py 

### ISSUE THREAD

**Issue by atermanini** [galaxyproject/ansible-galaxy-tools#38]
where is this file now?

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/ephemeris/blob/master/ephemeris/shed_install.py

The recommended way to use this is to do `pip install ephemeris` and then `shed-install <your options>`.

**Comment by atermanini** [comment]
Thanks, 

from the Galaxy Web site I found instructions to use Ansible with https://github.com/afgane/galaxy-tools-playbook.git, but for my installation it does not work.
So I was looking around and I found some tutorials using install_tool_shed_tools.py.

Is then ephemeris the right tool to use in order to install tools in galaxy?

Best
Alberto

**Comment by mvdbeek** [comment]
If you're not familiar with ansible, I would say yes, this is easier to setup and test.
This role makes use of ephemeris internally, so if your tool_list.yml file is fine, it should work both with this role and ephemeris.

I haven't had a chance to test this yet, but https://github.com/pjbriggs/nebulizer#managing-tools also looks like it's a great and easy way to install tools into galaxy.

**Comment by atermanini** [comment]
Well, I am new to galaxy installation and I am starting now making practices on Linux administration (Apache, MySQL and such common stuff). Ansible is new for me. So thanks a lot for your help, I hope to get galaxy tools installed :-)

Best,
Alberto

**Comment by atermanini** [comment]
Hello Marius,

I try a lot of times but I got a strange error.

shed-install --galaxy http://127.0.0.1:8080 --apikey 483f8c5f5e635acd701f19c5a7f1f653 --toolsfile tool_list.yaml;

with tool_list.yaml content:

tools:
- name: 'bowtie2'
  owner: 'devteam'
  tool_panel_section_label: 'My section'

If you would like to help me, I thank you very much!

Traceback (most recent call last):
  File "/usr/local/bin/python2.7.12/bin/shed-install", line 11, in <module>
    sys.exit(script_main())
  File "/usr/local/bin/python2.7.12/lib/python2.7/site-packages/ephemeris/shed_install.py", line 720, in script_main
    itm.install_tools()
  File "/usr/local/bin/python2.7.12/lib/python2.7/site-packages/ephemeris/shed_install.py", line 592, in install_tools
    itl = installed_tool_revisions(self.gi)  # installed tools list
  File "/usr/local/bin/python2.7.12/lib/python2.7/site-packages/ephemeris/shed_install.py", line 219, in installed_tool_revisions
    itl = tsc.get_repositories()
  File "/usr/local/bin/python2.7.12/lib/python2.7/site-packages/bioblend/galaxy/toolshed/**init**.py", line 36, in get_repositories
    return Client._get(self)
  File "/usr/local/bin/python2.7.12/lib/python2.7/site-packages/bioblend/galaxy/client.py", line 132, in _get
    raise ConnectionError(msg, body=r.text,
  File "/usr/local/bin/python2.7.12/lib/python2.7/site-packages/requests/models.py", line 796, in text
    if not self.content:
  File "/usr/local/bin/python2.7.12/lib/python2.7/site-packages/requests/models.py", line 772, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/bin/python2.7.12/lib/python2.7/site-packages/requests/models.py", line 705, in generate
    chunk = self.raw.read(chunk_size)
AttributeError: 'NoneType' object has no attribute 'read'

**Comment by mvdbeek** [comment]
You're having trouble listing the installed repositories on your server,
which is the first interaction with galaxy in the script.
Could you try including a terminal `/`, so that the command reads
```
shed-install --galaxy http://127.0.0.1:8080/ --apikey 483f8c5f5e635acd701f19c5a7f1f653 --toolsfile tool_list.yaml
```
If that doesn't work, which version of galaxy are you using?

**Comment by atermanini** [comment]
Thanks,

no it is not working with shed-install --galaxy http://127.0.0.1:8080/ --apikey 483f8c5f5e635acd701f19c5a7f1f653 --toolsfile tool_list.yaml

In the meantime I tried unsuccessfully shed-install--galaxy http://127.0.0.1:8080 --apikey 483f8c5f5e635acd701f19c5a7f1f653 --name bowtie2 --owner devteam --section mysect --section_label mylab --toolshed https://toolshed.g2.bx.psu.edu

My Galaxy comes from git clone -b release_16.07 https://github.com/galaxyproject/galaxy.git;

The API key is associated with the Admin user. I do not installed Ansible, is it correct?
I am running on an Amazon EC2 virtual machine with Red Hat Enterprise Linux Server 7.3

> Il giorno 21 nov 2016, alle ore 16:32, Marius van den Beek notifications@github.com ha scritto:
> 
> shed-install --galaxy http://127.0.0.1:8080/ http://127.0.0.1:8080/ --apikey 483f8c5f5e635acd701f19c5a7f1f653 --toolsfile tool_list.yaml

**Comment by atermanini** [comment]
I see now that galaxy/config folder does not contains a tool_sheds_conf.xml file, but tool_sheds_conf.xml.sample instead, I don’t know if this is correct

> Il giorno 21 nov 2016, alle ore 16:32, Marius van den Beek notifications@github.com ha scritto:
> 
> shed-install --galaxy http://127.0.0.1:8080/ http://127.0.0.1:8080/ --apikey 483f8c5f5e635acd701f19c5a7f1f653 --toolsfile tool_list.yaml

**Comment by mvdbeek** [comment]
> I see now that galaxy/config folder does not contains a tool_sheds_conf.xml file, but tool_sheds_conf.xml.sample instead, I don’t know if this is correct

if you're just running galaxy with run.sh this is OK.



> The API key is associated with the Admin user. I do not installed Ansible, is it correct?
> I am running on an Amazon EC2 virtual machine with Red Hat Enterprise Linux Server 7.3

This is all OK.

Can you install tools manually through galaxy's UI?

**Comment by atermanini** [comment]
yes all ok now, see screenshot, a reboot solved all, I don’t understand why, but I am happy :)

did you known where I can obtain a yaml file with the tools installed in use usegalaxy.org?
my group would like to have a sort of local mirror

**Comment by mvdbeek** [comment]
You can find this here: https://github.com/galaxyproject/usegalaxy-playbook/blob/master/files/galaxy/usegalaxy.org/tool_list.yaml

**Comment by atermanini** [comment]
Thanks very much for all your help!!

Best,
Alberto

**Comment by mvdbeek** [comment]
I'm gonna close the issue, if you have more problems don't hesitate to open a new issue.

**Comment by afgane** [comment]
Re. the file with the list of tools, the one linked higher up is a bit dated at this point. This file is a bit more recent although still no 100% match: https://github.com/galaxyproject/galaxy-cloudman-playbook/blob/master/files/usegalaxy_main_tool_list.yaml

**Comment by atermanini** [comment]
Thanks, I try it now
